// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNnJogb06LxcS6MoFKcUZGDV46_QVjhI0',
    appId: '1:974887919240:web:a70d3ac14f25f527d4493d',
    messagingSenderId: '974887919240',
    projectId: 'todolist-a3626',
    authDomain: 'todolist-a3626.firebaseapp.com',
    storageBucket: 'todolist-a3626.firebasestorage.app',
    measurementId: 'G-JDH0YQE870',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQzpjhveBYTk-9beRq75Imhr9MyI_0-ks',
    appId: '1:974887919240:android:b57e13a18d7abc17d4493d',
    messagingSenderId: '974887919240',
    projectId: 'todolist-a3626',
    storageBucket: 'todolist-a3626.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr6t_OOvchNoKwSgMUJrkdozrJFLt14_U',
    appId: '1:974887919240:ios:02d5d37c1f7a6232d4493d',
    messagingSenderId: '974887919240',
    projectId: 'todolist-a3626',
    storageBucket: 'todolist-a3626.firebasestorage.app',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr6t_OOvchNoKwSgMUJrkdozrJFLt14_U',
    appId: '1:974887919240:ios:02d5d37c1f7a6232d4493d',
    messagingSenderId: '974887919240',
    projectId: 'todolist-a3626',
    storageBucket: 'todolist-a3626.firebasestorage.app',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNnJogb06LxcS6MoFKcUZGDV46_QVjhI0',
    appId: '1:974887919240:web:4c23733621674050d4493d',
    messagingSenderId: '974887919240',
    projectId: 'todolist-a3626',
    authDomain: 'todolist-a3626.firebaseapp.com',
    storageBucket: 'todolist-a3626.firebasestorage.app',
    measurementId: 'G-2KFXVGKTLB',
  );

}